{
	"version": 1734943892,
	"fileList": [
		"data.js",
		"c2runtime.js",
		"jquery-3.4.1.min.js",
		"offlineClient.js",
		"images/assetsmemecube-sheet0.png",
		"images/bgloop-sheet0.png",
		"images/memesnake-sheet0.png",
		"images/coin-sheet0.png",
		"images/memesnake2-sheet0.png",
		"images/trigger1-sheet0.png",
		"images/sprite2-sheet0.png",
		"images/sprite-sheet0.png",
		"images/sprite-sheet1.png",
		"images/sprite-sheet2.png",
		"images/particles.png",
		"images/asset14x-sheet0.png",
		"images/asset14x-sheet1.png",
		"images/asset14x-sheet2.png",
		"images/asset14x-sheet3.png",
		"images/asset14x-sheet4.png",
		"images/asset14x-sheet5.png",
		"images/xmaschimneysanta-sheet0.png",
		"media/chimes.m4a",
		"media/chimes.ogg",
		"media/pop (1).m4a",
		"media/pop (1).ogg",
		"media/santa.m4a",
		"media/santa.ogg",
		"media/xmas game 2024 - bgm.m4a",
		"media/xmas game 2024 - bgm.ogg",
		"icon-16.png",
		"icon-32.png",
		"icon-114.png",
		"icon-128.png",
		"icon-256.png",
		"loading-logo.png"
	]
}