{
	"version": 1734952315,
	"fileList": [
		"data.js",
		"c2runtime.js",
		"jquery-3.4.1.min.js",
		"offlineClient.js",
		"images/bgloop-sheet0.png",
		"images/memesnake-sheet0.png",
		"images/coin-sheet0.png",
		"images/memesnake2-sheet0.png",
		"images/trigger1-sheet0.png",
		"images/sprite-sheet0.png",
		"images/sprite-sheet1.png",
		"images/sprite-sheet2.png",
		"images/particles.png",
		"images/asset14x-sheet0.png",
		"images/asset14x-sheet1.png",
		"images/asset14x-sheet2.png",
		"images/asset14x-sheet3.png",
		"images/asset14x-sheet4.png",
		"images/asset14x-sheet5.png",
		"images/xmaschimneysanta-sheet0.png",
		"images/d06825c9f91e4282822fb5a38da403c3photoroom-sheet0.png",
		"images/d06825c9f91e4282822fb5a38da403c3photoroom-sheet1.png",
		"media/chimes.m4a",
		"media/chimes.ogg",
		"media/pop (1).m4a",
		"media/pop (1).ogg",
		"media/santa.m4a",
		"media/santa.ogg",
		"media/grinch laugh.m4a",
		"media/grinch laugh.ogg",
		"media/meme pan hit sound effect.m4a",
		"media/meme pan hit sound effect.ogg",
		"media/xmas game 2024 - bgm.m4a",
		"media/xmas game 2024 - bgm.ogg",
		"icon-16.png",
		"icon-32.png",
		"icon-114.png",
		"icon-128.png",
		"icon-256.png",
		"loading-logo.png"
	]
}